all:
	g++ ./src/msgq_manager.cpp ./src/service_loader.cpp ./src/reactor.cpp ./src/netio.cpp -o netio -I./include -ldl
	g++ ./src/msgq_manager.cpp ./src/service_loader.cpp ./src/reactor.cpp ./src/container.cpp -o container -I./include -ldl